#!/bin/bash
if [ -z "$1" ]; then 
  echo usage: $0 testNumber jvmName
  exit
 fi
java -ea -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     cps.tenios.reseauEphemere.Test.DistributedCVM $1 $2 config.xml